logging:
  root: INFO
  file:
    path: D:/Maharishi International University/Enterprise Architecture/Project/OnlineRetailSystem/src/main/resources/logs
  org:
    springframework:
      boot:
        logging:
          LogLevel: INFO
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gid
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: kafka
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:postgresql://localhost:5432/OnlineRetailSystemNewWithJWT
    username: postgres
    password: test123
    driverClassName: org.postgresql.Driver
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  activemq:
    broker-url: tcp://localhost:6161
    user: admin
    password: admin
management:
  endpoints:
    web:
      exposure:
        include: beans,mappings,env
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
